# Generated by Django 5.2.13 on 2026-04-20 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentmetadata",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
