# Generated by Django 5.2.14 on 2026-06-01 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0003_resourcedocument"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="documentmetadata",
            name="is_approved",
        ),
    ]
